version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    volumes:
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1      

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    ports:
      - "5601:5601"
    environment:
      - "SERVER_NAME=localhost"
      - "ELASTICSEARCH_URL=http://elasticsearch:9200/"
    depends_on:
      - elasticsearch
    
  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    volumes: 
      - "./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml"
      # needed to persist filebeat tracking data :
      - "./data/filebeat/:/usr/share/filebeat/data:rw"      
      - "./logs/app.log:/var/log/sample/app.log:ro"
    depends_on:
      - elasticsearch
      - kibana      