filebeat.inputs:
  - type: log
    paths:
      - /var/log/sample/app.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.template.overwrite: true
setup.template.enabled: false
output.elasticsearch.index: "customname-%{[agent.version]}-%{+yyyy.MM.dd}"
setup.template.name: "customname"
setup.template.pattern: "customname-*"